name: Indian Market Automation Bot

on:
  workflow_dispatch:
  schedule:
    - cron: '*/3 * * * *' # हर 3 मिनट पर ऑटोमैटिक चलेगा

jobs:
  run-indian-market:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests yfinance openpyxl

      - name: Run Stock Alerts
        run: python Stock_Alerts.py

      - name: Run Bot
        run: python bot.py

      - name: Run Supersonic Scanner
        run: python "nse_Allrounder Supersonic Scanner_bot.py"

      - name: Run NSE Announcement Bot
        run: python nse_announcement_bot.py

      - name: Upload Scan Report (Artifact)
        uses: actions/upload-artifact@v4
        with:
          name: Chakravyuh-Result-Excel
          path: Chakravyuh_Verified_Breakouts.xlsx
          if-no-files-found: ignore
